### ISSUE TITLE
Notes are not visible with the dark theme

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge.org#12]
The note block is not visible with the dark website theme:
https://blog.korge.org/korge-tutorial-writing-2048-game-step-3-animation

<img width="576" alt="2022-12-07_21h15_09" src="https://user-images.githubusercontent.com/1190109/206286461-dc6df2fc-65a1-49fb-8d42-40d2142252c7.png">

**Comment by soywiz** [comment]
Fixed
