### ISSUE TITLE
feat: Add syntax highlighting for code samples

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge.org#13]
Would be nice to get a Kotlin syntax highlighting for the code blocks for the tutorial:

https://blog.korge.org/korge-tutorial-writing-2048-game-step-3-animation
It's just rendered in black:
<img width="356" alt="2022-12-07_21h21_19" src="https://user-images.githubusercontent.com/1190109/206287399-9cb2e5cd-aec9-4ac4-9d02-6b06ea078165.png">

**Comment by soywiz** [comment]
Done
